name: Run phpunit test suite

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD:
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1]
        cms: [dev-master]
        version: [dev-develop]
    name: PHP${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer create-project --prefer-dist juzaweb/cms blog ${{ matrix.version }}
      - name: Generate key
        working-directory: blog
        run: php artisan key:generate
      - name: Clear Configuration
        working-directory: blog
        run: php artisan config:clear
      - name: Directory Permissions
        working-directory: blog
        run: chmod -R 777 storage bootstrap/cache
      - name: Update package
        working-directory: blog
        run: composer require juzaweb/modules:${{ matrix.cms }}
      - name: Install Example plugin for Testing
        working-directory: blog
        run: composer require juzaweb/example:${{ matrix.cms }}
      - name: Execute tests Install
        working-directory: blog
        run: php artisan test vendor/juzaweb/modules/modules/Tests/InstallTest.php
      - name: Execute tests (Unit and Feature tests)
        working-directory: blog
        run: php artisan test
      - name: Execute tests disabled frontend
        working-directory: blog
        run:
          php artisan test vendor/juzaweb/modules/modules/Tests/Feature/Auth
          php artisan test vendor/juzaweb/modules/modules/Tests/Feature/Backend
        env:
          JW_FRONTEND_ENABLE: false
